### ISSUE TITLE
installation location is not getting cleaned up for Jenkins build

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/groffport#1]
The installation script that cleans up the Jenkins installation directory before doing the pax is being foiled with man pages because the '-' is being escaped so that it is a valid string in for the man page, e.g.

* ./share/man/man1/nroff.1:  *

```
  .I /jenkins/workspace/Port\-Build/install
```

A _proper_ fix for this is likely a bit involved. A _simple_ fix for now would be to change the jenkins installation location to not have a `-` in it, e.g.

```
/jenkins/workspace/PortBuild/install
```

which would then not have to be escaped.

@IgorTodorovskiIBM assigning to you if you're willing to change the Jenkins directory. If not, I will see if there is another solution to the problem (this causes man-db to not pass as many tests as it should).

**Comment by IgorTodorovskiIBM** [comment]
Sure, I've changed the directory to PortBuild.
